[package]
name = "copper"
version = "0.1.0"
authors = ["umicheal32 <mikyou16@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.61"
rand = "0.8.0"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"